### PR TITLE
Simplify deploy, reduce logs visible to players

### PR DESCRIPTION
**Pull request by Pathoschild**
This pull request...

* Adds the `assets` folder to the mod folder and release zip automatically when you build.
* Hides troubleshooting messages from the player console (they'll still be shown in the log).

Let me know if you want me to change anything!

### CODE REVIEW

**Comment by Pathoschild** [comment]
Also, your changes in 0d033de466e5d05d045fbc1833273a6fe1477f4c fix compatibility with [an upcoming SMAPI 3.0 change](https://stardewvalleywiki.com/Modding:Migrate_to_SMAPI_3.0#Mods_are_loaded_earlier); could you release that soon to avoid issues when 3.0 is released?

**Comment by maxvollmer** [comment]
Thank you! As for the release - any chance this feature makes it into 3.0? https://github.com/Pathoschild/SMAPI/issues/615

I was planning to do one final version of Deep Woods where I'd make use of this feature and was waiting for it as it was marked as 2.11 feature, but see now that it changed to unplanned proposal. I could also implement that feature if you are okay with code from someone who is at home in Java and C++ :D

**Comment by Pathoschild** [comment]
It probably won't be in 3.0, but contributions are welcome! I mainly held off on adding it because...

1. I'm concerned the API would be misleading and of limited use. It only lists mods which intercepted the asset through the content API, but mods often edit data after it's loaded.
2. For mods like Content Patcher, the method would return the main mod rather than the content pack it was intercepted for (which makes it basically useless for content pack changes).

**Comment by maxvollmer** [comment]
@Pathoschild Just a heads-up, Deep Woods 1.6-beta.0 with SMAPI 3.0 support has been released.

**Comment by Pathoschild** [comment]
Thanks! I updated the compatibility list.

**Pull request merged**
