### PR TITLE
Adjusted code to handle all obsolete warnings noticed in SMAPI 3.16.2

### PR DESCRIPTION
**Pull request by Ajohn10**
I don't have a way to thoroughly test this since this is my first commit for a stardew mod, so if you have any save files that are easier to test the functionality of these, I would recommend it to cover all bases.  I ran the game and was able to enter the deep woods and walk around for a while with no issues.

### CODE REVIEW

**Comment by TinyFingersBigMessages** [comment]
Heck yeah! Awesome! Cannot wait to test it. 🥳 

Is there a precompiled version available?

**Comment by Ajohn10** [comment]
This is a link to the zip file it builds.  (I didn't bother adjusting the version, figured maxvollmer could do that if he accepts the pull request) 

https://drive.google.com/file/d/1RiknuUN_qHUWYiWnWRWSMbgSSx3NbHLN/view?usp=sharing

**Comment by maxvollmer** [comment]
Thanks for that! I am going to reject the PR tho, because I already have fixes for these warnings and will upload a new version in the very near future. Btw, you should always adjust the version if you release a new build. If you don't want to interfere with potential future versions I may release, you can append an identifier, e.g. `2.0.0-beta.inofficial.ajohn10`.

**Comment by Ajohn10** [comment]
It's possible to adjust code in a pull request.  I don't know the way you version, so I chose to wait for your input.  It was a decision made to respect your practices rather than enforcing my own, since it isn't my project.

In the future, if it is an effective PR, I would recommend not rejecting simply due to the fact that you will have it fixed in the near future.  A far better practice would be to accept the PR and then pull the change into your current branch, favoring the one you have been working on.  As it is, the way you handled that indicates you don't want help.  Meaning I won't assist in this repository any further.  If that is actually the case, then restrict the repository from allowing pull requests.

**Comment by maxvollmer** [comment]
If you can't handle PRs being rejected, you probably shouldn't be creating PRs, yes. I thanked you for your effort, explained why I closed the PR, and told you how to handle versions in the future. If that pisses you off, that's coming from you, not me. Seriously, work on that anger. Go for a walk. Scream into a pillow. Write a poem. I dunno. But don't unload it here. My life is too short for this negative energy. Take care.

**Comment by Ajohn10** [comment]
That was legitimate advice, not anger (though probably annoyance, since I did help, though the time went to waste).  Merging is a very simple process, and a far better solution.  From my perspective, you don't desire assistance, which is why I am recommending to make the repository restricted from pull requests. 

As the current contribution to this is pretty low, I can't expect feedback that you are currently working on something, but indication that a feature is being worked on would also be a potentially nice indicator of what not to work on for future contributors.  From my perspective, it had appeared like this mod was not currently being supported, based on comments on the other open PR.

**Comment by maxvollmer** [comment]
Fair. Okay, multiple things going on here:

1. The other PR is about a new feature. This PR is about a fix. I have always maintained the mod with fixes and updates to stay compatible with SMAPI and the game.

2. You could have asked if I need help on this.

3. Merging is not the better solution. Why would it be? It would create extra work for me. Since I already have these fixes completed and tested, why would I merge yours? You said yourself you didn't thoroughly test your changes.

4. Your time did not go "to waste". Writing code that doesn't get merged or used is a perfectly normal part of software development, especially in collaborative environments. You still had the learning experience of diving into a SMAPI mod, figuring out the code, and implementing something new. That's valuable in and off itself. Merging or closing this PR neither adds value, nor does it take away from what you did.

Look, I get you were frustrated, maybe taken by surprise. But there really is no need for that. A PR getting closed is a normal procedure that neither devalues your work, nor does it mean it's not appreciated. Merging it would simply create extra work for me. Closing it was the simplest solution.

If you want to contribute in the future, you are more than welcome. If you want to avoid PRs getting closed, talk to me before you work on something.

**Pull request closed without merging**
